### ISSUE TITLE
Cosas nuevas 

### ISSUE THREAD

**Issue by edgarimtc** [edgarimtc/PercepcionN5_10#1]
Hoy mi perro hizo cosas nuevas, se escapo de mi casa y volvió. Pienso que seria bueno agregarlo al poema.
![perro](https://user-images.githubusercontent.com/42400280/44502911-37025500-a659-11e8-900c-d6d7aafe41ad.jpg)

**Comment by Jibs2194** [comment]
quedo listo en el poema
