### ISSUE TITLE
Logros 

### ISSUE THREAD

**Issue by edgarimtc** [edgarimtc/PercepcionN5_10#2]
Pienso que esto seria muy bueno agregarlo al poema, ya que mi perro logro darse vueltas y sentarse.

![18 01 2015_16 27dsc02239](https://user-images.githubusercontent.com/42400280/44503210-c2c8b100-a65a-11e8-91a0-eb6065127dd7.jpg)

**Comment by Jibs2194** [comment]
he añadido los logros de tu canhijo :p
